"""add owner_id and updated_at

Revision ID: b31840eef9c6
Revises: d226d036d711
Create Date: 2026-07-12 21:26:13.945258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31840eef9c6'
down_revision: Union[str, Sequence[str], None] = 'd226d036d711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('audio_files', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_audio_files_owner_id'), 'audio_files', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_files_owner_id'), table_name='audio_files')
    op.drop_column('audio_files', 'updated_at')
    op.drop_column('audio_files', 'owner_id')
    # ### end Alembic commands ###
