apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-voice-transcriber.fullname" . }}-config
  labels:
    {{- include "ai-voice-transcriber.labels" . | nindent 4 }}
data:
  DATABASE_HOST: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  FILE_DATABASE_NAME: "file_db"
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}

  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}

  MINIO_ENDPOINT: {{ printf "%s:%v" .Values.minio.host .Values.minio.apiPort | quote }}
  MINIO_BUCKET: {{ .Values.minio.bucket | quote }}
  MINIO_SECURE: "false"
