apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.port }}
      targetPort: {{ .Values.rabbitmq.port }}
    - name: management
      port: {{ .Values.rabbitmq.managementPort }}
      targetPort: {{ .Values.rabbitmq.managementPort }}
  selector:
    app.kubernetes.io/name: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - containerPort: {{ .Values.rabbitmq.port }}
            - containerPort: {{ .Values.rabbitmq.managementPort }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-voice-transcriber.fullname" . }}-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-voice-transcriber.fullname" . }}-secret
                  key: RABBITMQ_PASSWORD
