apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-voice-transcriber.fullname" . }}-secret
  labels:
    {{- include "ai-voice-transcriber.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_USER: {{ .Values.secrets.postgresUser | quote }}
  DATABASE_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}

  RABBITMQ_USER: {{ .Values.secrets.rabbitmqUser | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}

  MINIO_ACCESS_KEY: {{ .Values.secrets.minioRootUser | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioRootPassword | quote }}